### ISSUE TITLE
SE Studio Fidelity Checklist 2: Planning Meeting with Researcher/Research Team 

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#10]
- [ ] PI, Navigator and facilitator meet together.

- [ ] SE Studio process is explained/clarified.

- [ ] SE Studio group rules are explained to researcher/research team. 

- [ ] Questions to be posed to Stakeholders are proposed/drafted (2-3 max, open-ended).

- [ ] Characteristics of Stakeholder panel are defined. 

- [ ] Stakeholder experts are coached on effective communication.

- [ ] Study presentation template with guidelines for completion (provided to researcher).

- [ ] Identify possible dates for SE Studio (3-4 dates).

**Comment by rachelduggan10** [comment]
should "stakeholder experts" be changed to "studio participants?"
