### ISSUE TITLE
SE Studio Fidelity Checklist 3: Stakeholder Studio Team 

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#11]
- [ ] Identify neutral facilitator.

- [ ] Confirm navigator's availability.

- [ ] Identify support staff to help with recruitment/logistics.

- [ ] Develop facilitator's guide (3 main questions and probes).

- [ ] Vet researcher's presentation.

- [ ] Researcher and facilitator review final research's presentation and facilitator's guide.

- [ ] Recruit and screen stakeholder participants for expert panel.

- [ ] Review compensation expectations (length of time to complete compensation, type of gift card etc.).
