### ISSUE TITLE
SE Studio Fidelity Checklist 4: Community Experts

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#12]
- [ ] Ensure no relationship with researcher/research team.

- [ ] Affirm experts representation/membership of stakeholder group of interest.

- [ ] Provide orientation to SE Studio and explain compensation.

- [ ] Provide study materials to stakeholder experts for review, in advance if necessary.

- [ ] Experts complete application (for future SE Studio opportunities).
