### ISSUE TITLE
SE Studio Fidelity Checklist 5: Logistics 

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#13]
- [ ] Poll experts for optimal data and location of SE Studio.

- [ ] Secure meeting room at location with convenient parking and/or transit options.

- [ ] Ensure access to computer, projector and power cords. 

- [ ] Ensure digital access to presentation (thumb drive, internet).

- [ ] Order food order, considering dietary restrictions or needs (for experts and research team).

- [ ] Print forms: Sign-in sheet, paperwork for expert payment, evaluation surveys, expert comment form.

- [ ] If needed, print research materials for review (flyers, brochures, surveys).

- [ ] Gather supplies (markers, pens, flip charts, name tags),

- [ ] Gift cards for payment, if used. 

- [ ] Confirm time and location with researcher and experts, including directions, parking,   contact info.
