### ISSUE TITLE
SE Studio Fidelity Checklist 6: Stakeholder Studio Event 

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#14]
- [ ] SE Studio team present.

- [ ] No more than two members of research team in attendance.

- [ ] Approx. 8 to 10 expert panel members in attendance.

- [ ] Welcome and instructions.

- [ ] Overview of ground rules: First names, everyone sit at table, no wrong answers, different opinions are encouraged, everyone on panel participants, do not talk over   others; Housekeeping: location of restrooms, turn of cell phones and devices.

- [ ] 10 minute presentation by PI, followed by very brief Q & A for clarification.

- [ ] Facilitator uses facilitation guide to direct conversation.

- [ ] Facilitation techniques used to balance power, include all voices, empower experts, validate experts’ comments, stay on focus.

- [ ] Navigator takes notes on flip charts, visible to all.

- [ ] Facilitator reviews expert responses, recommendations for affirmation, validation.

- [ ] Experts complete written comments form.

- [ ] Evaluations completed by researcher and experts.

- [ ] Compensation/gift cards expended, signed for.
