### ISSUE TITLE
SE Studio Fidelity Checklist 7: Follow Up 

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#15]
- [ ] Send ‘Thank you’ to stakeholder experts.

- [ ] Make sure payment is sent to experts in timely manner, if gift cards are not used.

- [ ] Type up summary of SE Studio discourse for researcher (includes expert comments plus specific recommendations).

- [ ] Contact researcher if additional information or assistance with recommendations is   needed.

- [ ] Report back to experts on actions/changes made as a result of their input (may take 3 to 6 months or more, depending on project).
