### ISSUE TITLE
SE Studio Fidelity Checklist: Facilitation 

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#16]
- [ ] Use opener to engage each expert at the beginning, by going around the room and asking: “What are your initial thoughts about the project?”.

- [ ]  Call each person by their name to establish rapport as opposed to general use of ‘you'.

- [ ]  Don’t ask close-ended (yes/no) questions.

- [ ] Ask experts to elaborate on short answers; avoid interjecting personal experiences and opinions.

- [ ] Use body positioning to redirect conversation or address dominate experts.

- [ ] Limit researcher/staff commentary.

- [ ] Refocus experts as needed by restating/rewording question.

- [ ] Create ‘parking lot’ for issues that are not specific to discussion.

- [ ] Give time reminders to move discussion along, as needed.

- [ ] Be comfortable with silences to give experts time to think and respond.
