### ISSUE TITLE
SE Studio Fidelity Checklist: Recordkeeping

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#17]
- [ ] Enter new experts in stakeholder data base.

- [ ] Process evaluation surveys.

- [ ] Update SE Studio record data database.
