### ISSUE TITLE
SE Studio Fidelity Checklist 1: Pre-Planning

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#9]
- [ ] Application filed: Brief description of project, population of interest, nature of project challenge. (Application GitHub link)
- [ ] Confirm SE Studio is correct approach for researcher's focus. (Need for studio GItHub link) 
- [ ] Identify facilitator based on relevant stakeholder characteristics/demographics.
- [ ] Schedule planning meeting and share SE Studio FAQ.
